{{# written 6 aug, 2026 #}}
typewriter: {
    charDelay: 46
    newlineDelay: 600
    textColor: #ffffff
    backgroundColor: #000000
    customDelays: {
        ",": 400
        ".": 600
        ":": 150
        "–": 500
    }
    wordWrap: 110
}
[function "userinput" "type here: "][newline]
wow bye hello wow hi woww wowwowowowowowwo wow wow wow wow wow wow

{{# wow hi /*[function "sine" 17 0.6 1][gradient "what the fuck!!!!" "90deg, #c8d8fb, #6f6fff"]/* #}}