{{# written 6 aug, 2026 #}}
typewriter: {
    charDelay: 46
    newlineDelay: 200
    textColor: #ffffff
    backgroundColor: #000000
    customDelays: {
        ",": 400
        ".": 600
        ":": 150
        "–": 500
    }
    wordWrap: 110
}
big long string[removelast 15]
big long string[removelast 15 instant]
{{# [function "progress-bar" "=" 100] #}}
{{# [function "input" "type here: " false][newline]
last user input: [function "lastsentinput"][newline]
/*[function "sine" 17 0.6 1][gradient "what the fuck!!!!" "90deg, #c8d8fb, #6f6fff"]/* #}}