typewriter: {
    charDelay: 50
    newlineDelay: 800
    textColor: #ffffff
    backgroundColor: #000000
    wordWrap: 80
    customDelays: {
        ",": 350
        ".": 600
        ":": 600
        "?": 600
    }
}
[sleep 1000]
[tab 6]From: [speed 80 override]tgardinier@lassel.um.orri[speeddefault][newline]
[tab 6]Sent: [speed 80 override]August 14th,[sleep 500] 2313[sleep 500] 18:40:25 SST[newline]
[tab 8]To: [speed 80 override]kdevine@falstaff.ob.orri[speeddefault][newline]
[tab 3]Subject: [speed 80 override]Strange Data[speeddefault][newline]
Attachment: [speed 80 override]data.fits[speeddefault][newline]
[newline]
Hey Kent,[linebreak]
[speed 40]
I recently collected this data, but I ran into an issue trying to read it. It said the file’s corrupted, and I don’t have the tools over here to scrape the data out myself. Could you take a look at it [sleep 500](when you have the time)?[newline]
[newline]
\-Tom, Lassel Outpost
[linebreak]
[sleep 500]
[gopage "2" "Next >"]

[page "2"]
[sleep 1000]
[tab 6]From: [speed 80 override]kdevine@falstaff.ob.orri[speeddefault][newline]
[tab 6]Sent: [speed 80 override]August 14th,[sleep 500] 2313[sleep 500] 19:26:51 SST[speeddefault][newline]
[tab 8]To: [speed 80 override]tgardinier@lassel.um.orri[speeddefault][newline]
[tab 3]Subject: [speed 80 override]Re:[sleep 520] Strange Data[speeddefault][newline]
[newline]
[speed 40] 
Thomas,[sleep 800][linebreak]
I’m a bit backed up with work at the moment, but I’ll see what I can do. I’ll most likely get to it tomorrow or the day after.[newline]
[newline]
\-K[speed 40 override].[speeddefault][speed 40] Devine, Falstaff Station
[linebreak]
[sleep 800]
[gopage "3" "Next >"]
[page end]

[page "3"]
[sleep 1000]
[tab 6]From: [speed 80 override]tgardinier@lassel.um.orri[speeddefault][newline]
[tab 6]Sent: [speed 80 override]August 14th,[sleep 500] 2313[sleep 500] 19:28:05 SST[speeddefault][newline]
[tab 8]To: [speed 80 override]kdevine@falstaff.ob.orri[speeddefault][newline]
[tab 3]Subject: [speed 80 override]Re:[sleep 520] Re:[sleep 520] Strange Data[speeddefault][newline]
[newline]
[speed 80]
Thank you![sleep 900][newline]
[newline]
\-Tom, Lassel Outpost
[linebreak]
[sleep 1000]
[gopage "4" "Next >"]
[page end]

[page "4"]
[tab 6]From: [speed 80 override]kdevine@falstaff.ob.orri[speeddefault][newline]
[tab 6]Sent: [speed 80 override]August 15th,[sleep 500] 2313[sleep 500] 12:16:20 SST[speeddefault][newline]
[tab 8]To: [speed 80 override]tgardinier@lassel.um.orri[speeddefault][newline]
[tab 3]Subject: [speed 200 override]WHAT THE FUCK[speeddefault][newline]
[speed 100 override]Attachment: data.txt[newline]
[newline]
[speed 200]
(no body)
[speeddefault]
[linebreak]
[sleep 1400]
[gopage "5" "Next >"]
[page end]

[page "5"]
[speed 125 override]Attachment:[sleep 800] data.[sleep 400]txt[speeddefault][newline]
[newline]
[speed 180]
He[sleep 100]llo.[sleep 1000][newline]
We see you.[sleep 1000][newline]
You are new to us.[sleep 1000][newline]
We will help you.[sleep 1000][newline]
But [speed 195]do not[speed 180] fri[sleep 120]ghten us.[sleep 1000][newline]
Happy.[sleep 1000][newline]
Be happy.[sleep 1000][newline]
Happy.[sleep 1500][newline]
Goodbye.[sleep 2000][linebreak]

[sleep 700][function "end"]
[page end]