{{# written 18 july, 2026 #}}
typewriter: {
    charDelay: 55
    newlineDelay: 800
    textColor: #ffffff
    backgroundColor: #000000
    customDelays: {
        ",": 350
        ".": 600
        ":": 600
        "?": 600
    }
    wordWrap: 72
}

[sleep 1000]

    [tab 6]From: [speed 70 override]tgardinier@lassel.um.orri[speeddefault][newline]
    [tab 6]Sent: [speed 70 override]August 14th,[sleep 500] 2313[sleep 500] 18:40:25 SST[speeddefault][newline]
    [tab 8]To: [speed 70 override]kdevine@falstaff.ob.orri[speeddefault][newline]
    [tab 3]Subject: [speed 70 override]Strange Data[speeddefault][newline]
    Attachment: [speed 70 override]data.fits[speeddefault][newline]

    [newline]

    Hey Kent,[linebreak instant][sleep 440]

    [speed 50]
    I recently collected this data, but I ran into an issue trying to read it. It said the file’s corrupted, and I don’t have the tools over here to scrape the data out myself. Could you take a look at it ([sleep 380]when you [speed 40]have the[speed 50] time)[sleep 300]?[linebreak]

    [sleep 50]

    \-Tom,[sleep 320] Lassel Outpost

    [linebreak instant]
    [sleep 1080]

[gopage "1" "Next >"]

[page "1"]

    [sleep 1000]

    [tab 6]From: [speed 70 override]kdevine@falstaff.ob.orri[speeddefault][newline]
    [tab 6]Sent: [speed 70 override]August 14th,[sleep 500] 2313[sleep 500] 19:26:51 SST[speeddefault][newline]
    [tab 8]To: [speed 70 override]tgardinier@lassel.um.orri[speeddefault][newline]
    [tab 3]Subject: [speed 70 override]Re:[sleep 520] Strange Data[speeddefault][linebreak]

    [speed 50] 
    Thomas,[linebreak]

    I’m a bit backed up with work at the moment, but I’ll see what I can do. I’ll most likely get to it tomorrow or the day after.[linebreak]

    \-K[speed 50 override].[speeddefault][speed 50] Devine,[sleep 280] Falstaff Station

    [linebreak instant]
    [sleep 1100]
    [gopage "2" "Next >"]
[page end]


[page "2"]
    [sleep 1000]

    [tab 6]From: [speed 70 override]tgardinier@lassel.um.orri[speeddefault][newline]
    [tab 6]Sent: [speed 70 override]August 14th,[sleep 500] 2313[sleep 500] 19:28:05 SST[speeddefault][newline]
    [tab 8]To: [speed 70 override]kdevine@falstaff.ob.orri[speeddefault][newline]
    [tab 3]Subject: [speed 70 override]Re:[sleep 520] Re:[sleep 520] Strange Data[speeddefault][linebreak]

    [speed 50]
    Thank you![sleep 500][linebreak]

    \-Tom,[sleep 320] Lassel Outpost

    [linebreak instant]
    [sleep 1100]
    [gopage "3" "Next >"]
[page end]

[page "3"]
    [tab 6]From: [speed 70 override]kdevine@falstaff.ob.orri[speeddefault][newline]
    [tab 6]Sent: [speed 70 override]August 15th,[sleep 500] 2313[sleep 500] 12:16:20 SST[speeddefault][newline]
    [tab 8]To: [speed 70 override]tgardinier@lassel.um.orri[speeddefault][newline]
    [tab 3]Subject: [speed 150 override]WHAT THE FUCK[speeddefault][newline]
    [speed 100 override]Attachment: data.txt[speeddefault][linebreak]

    [speed 100]
    (no body)

    [speeddefault]

    [linebreak]

    [sleep 1200]

    [gopage "4" "Next >"]
[page end]

[page "4"]
    [speed 125 override]Attachment:[sleep 800] data.[sleep 400]txt[speeddefault][newline]
    [newline]
    [speed 180]
    He[sleep 300]llo.[sleep 1000][newline]
    We [speed 60]sssss[removelast 4][speed 180]ee you.[sleep 1000][newline]
    You a[sleep 200]re new to us.[sleep 1000][newline]
    We [sleep 182]wil[speed 120]l help[speed 160] you.[sleep 1000][newline]
    But [speed 195]do not[speed 180] fri[sleep 120]ghten us.[sleep 1000][newline]

    H[speed 7]aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa[removelast 33][speed 120]ppy.[sleep 1200][newline]
    [speed 180]Be ha[sleep 80][speed 220]ppy.[sleep 1200][newline]
    [speed 240]Ha[sleep 220]ppy.[sleep 1200][newline]
    [speed 220]Go[speed 80]0[removelast 1][speed 230]odbye.[sleep 1100][linebreak]

    [sleep 700][function "end"]
[page end]