{{# written 6 aug, 2026 #}}
typewriter: {
    charDelay: 46
    newlineDelay: 600
    textColor: #ffffff
    backgroundColor: #000000
    customDelays: {
        ",": 400
        ".": 600
        ":": 150
        "–": 500
    }
    wordWrap: 110
}
[repeat "repeat" 3][newline]
[repeat 3]
    I can repeat /so many/ things![newline]
[repeat end][linebreak]


{{# wow hi [sleep 1000][speed 1000]/*[function "sine" 3 0.6 1][gradient "Sky" "90deg, #c8d8fb, #6f6fff"]/* #}}