{{# written 21 july, 2026 #}}
typewriter: {
    charDelay: 20
    newlineDelay: 200
    textColor: #ffffff
    backgroundColor: #000000
    customDelays: {
        ",": 300
        ".": 400
        ":": 300
    }
    wordWrap: 150
    backToTop: true
}
hiiii[newline]


[function "set image channel shift" "rb" 1000]
[function "set image bit corrupt" 1]
[function "set image block glitch" 50 100]
[function "set image wave distort" 10 1000]
[function "set image hue rotate" 100 500]

{{#src, width, height, speed#}}
[function "image" "img-to-st/test-img-NOT-MINE.png" 312 438 100][newline]
hello!
