{{# written 11 sept, 2026 #}}
typewriter: {
    charDelay: 35
    newlineDelay: 750
    textColor: #ffffff
    backgroundColor: #000000
    customDelays: {
        ",": 350
        ".": 600
        "”": 400
    }
    wordWrap: 100
}

This report documents a series of events. Due to similarities between the following data, and to that from the Gardinier Message, ORRI has concluded that the data contained herein, and that of the former, share an origin. The events documented in this report have been consequently designated as “Second Contact,” or, in more general terms, the “Neptune Corridor Incidents.” All incidents occured along the Neptune Corridor, between ITA Basilica and ITA Actium Stations, endward, but at multiple points throughout.[linebreak][gopage "a" "Incident A >"]

[page "a"]
    Incident A[newline]
    Time: June 7, 2317 05:12:\-\- SST[newline]
    Approximately 142 hours into her journey, /Lucky Toss,/ a Yargon\-class hauler, and her crew observed, what was described by witnesses, as a large “explosion” between approximately [ignore]10,000 to 50,000[ignore off] kilometers off of the port side of the vessel. Approximately seven minutes later, all optical, radar, and lidar sensors simultaneously went offline.[linebreak][gopage "b" "Incident B >"]
[page end]

[page "b"]

Incident B[newline]
Time: August 12, 2317 14:\-\-:\-\- SST[newline]
Approximately 10 minutes into her journey, /Marketman,/ a Mars\-class Starliner Cruiser, and her crew observed through a window an abnormal light flashing above the vessel. Upon review of optical recordings, the flashing was determined to be an Old Earth\-style method of long\-distance communication once known as “Morse Code.” The Morse Code was deciphered by ORRI researchers as follows:[linebreak]

[speed 179 override]Hello.Hello.Hello.Hello.Hello.[speeddefault][linebreak]

As the vessel had not yet fully left ITA Basilica space, ORRI field researchers interviewed many civilians who were inside of the station, and were proven to be standing near windows facing the message. However, none reported finding any witnesses. Review of external station cameras proved futile.[linebreak][gopage "c" "Incident C >"]
[page end]

[page "c"]
    Incident C[newline]
    Time: December 10, 2317 09:12:28 SST[newline]
    270 hours, 16 minutes, and 30 seconds into her journey, /High Pitch,/ a Pioneer\-class Helium Mining Barge, experienced a momentary total loss of pilot\-controlled flight navigation, during which its navigational functions were temporarily taken over. The computer received a signal, from an unknown source, to deviate 86° yaw, [ignore]47.5[ignore off]° pitch, and continue for [ignore]33,587.771[ignore off] kilometers.[linebreak]

    After 2 minutes and 1 second, the pilot noticed the overridden destination, and attempted to regain control of the navigational computer. After several unsuccessful attempts to do so lasting 4 minutes and 12 seconds, the pilot determined that were unable to regain control of the navigational computer, and elected to follow protocol.[linebreak]

    In the event that the pilot is unable to control the navigational computer, they are to retrieve all non\-tampered pertinent information, and destroy the navigational computer in a controlled environment.[linebreak]

    After destruction, the pilot engaged RMC 1 in navigational mode, and uploaded all retrieved navigational information. The pilot was able to return the vessel to its position in the Neptune Corridor with minimal delays in arrival time.[linebreak]

    Post\-arrival diagnostics determined that the navigational computer had sustained no hardware damage other than the controlled destruction. All recorded commands issued during the incident were found to be valid. All recorded commands issued during the incident were found to be originating from the navigational computer itself. No corresponding inputs were found in the vessel’s control systems log. Witnesses in the cockpit corroborate that no member of the crew interacted with the navigational computer during the incident, other than to attempt to regain control.[linebreak]

    Further examination of recovered navigational data revealed that the commanded destination did not correspond to any registered station, vessel, waypoint, or any other navigational destination within [ignore]100,000,000[ignore off] kilometers of the Neptune Corridor. The coordinates placed the vessel on a trajectory toward an unknown point beyond the established shipping lanes.[linebreak]

    Of particular note, the transmitted course correction contained no identifying information, authorization code, source origin, or override code. ORRI researchers were unable to determine how the command had been received or executed, as the hardware of this particular vessel will only execute external commands if identifying information and at least two other criteria are present.[linebreak][gopage "d" "Incident D >"]
[page end]

[page "d"]
    Incident D[newline]
    Time: January 7th, 2318 02:20:13 SST[newline]
    \174 hours and 30 minutes into her journey, /Sunday’s Request,/ an Arecibo\-class Cruiser, received an audio message. After which her crew of two emergency hailed the nearest vessel, which was answered by /Texas Creamery,/ an Evergreen\-class freighter. During questioning, the crew of /Sunday’s Request/ stated that they, quote, “did not want to be alone.”[linebreak]

    ORRI researchers were unable to determine the message’s point of origin.[linebreak]
    
    A transcript of the message is as follows:[sleep 1430][linebreak]
    [custom "\n" 2100][speed 40]

    \[indistinct noise for [ignore]5.37[ignore off] seconds\][linebreak]

    \[hollow, metallic banging, slowly growing louder for [ignore]10.3[ignore off] seconds\][linebreak]

    \[scraping of metal lasting [ignore]0.83[ignore off] seconds\][linebreak]

    \[a deep and low thump, no echo. single occurrence\][linebreak]

    \[low, dry screeching, followed by several wet, strained vocalizations, as though the speaker is attempting to clear its throat, lasting [ignore]8.22[ignore off] seconds\][linebreak]

    \[pause lasting [ignore]1.7[ignore off] seconds\][sleep 6028][linebreak instant]
    
    [speed 200][custom "\n" 3000]
    [speed 210][jitter "Our great he" 7][speed 290]li[speed 201][sleep 120][jitter "x h" 8][speed 190][jitter "as " 4][sleep 200][jitter "come to y" 6][speed 195]ou.[newline]
    Rej[sleep 500]oice[jitter "." 10][newline]
    [jitter "B" 7][jitter "e" 5] [jitter "happ" 12][speed 50][repeat 10][removelast 1]p[repeat end][speed 200]y.[newline][sleep 899]
    We [sleep 39][jitter "have com" 6][jitter "e" 7].[newline]
    [jitter "Be ha" 4][jitter "p" 3]py.[newline]
    [jitter "We saw you." 6][newline]
    [jitter "Our " 3 shared][jitter "home " 3 shared][sleep 120][jitter "is " 3 shared][jitter "gone." 3 shared][newline]
    [jitter "We c" 8][jitter "ome" 9][sleep 200] to [jitter "you" 4].[newline]
    We prepared.[newline]
    [jitter "Not e" 5][sleep 130][jitter "nough." 5][newline]
    [jitter "Only us." 10][newline]
    [jitter "We offer yo" 15][sleep 333][jitter "u." 15][newline]
    [jitter "Give us home." 20][newline]
    [jitter "And we will share." 35][newline]
    [jitter "What we k" 55][sleep 544][jitter "now." 55][newline]
    [jitter "To you." 45][custom "\n" 500][linebreak]

    [speed 40]
    [sleep 2820]\[At this point, the speech becomes unintelligible, whether through vocal straining or audio signal corruption\][sleep 500]
    [speed 200]

    [linebreak][newline][custom "\n" 3000] 
    [function "jitterlerp" "êh÷nā ďoċ üoĈ Ĉeùiûvÿný ċsÄ" 250 300][newline]
    [function "jitterlerp" "OůrĚpśnũpŮiŝoŨ." 50 200][newline]
    [function "jitterlerp" "ɨeɆhʇpʖyɔ" 250 500][linebreak][newline instant][linebreak instant]

    [speed 40]
    [sleep 4550]\[The speaker coughs, and cries in pain. A wet, splattering sound can be heard\][sleep 2400]


    [linebreak instant]
    End of transcript.[linebreak]
    End of report.[linebreak instant]
    [sleep 1700][function "end"]
[page end]
