{{# written 6 aug, 2026 #}}
typewriter: {
    charDelay: 46
    newlineDelay: 600
    textColor: #ffffff
    backgroundColor: #000000
    customDelays: {
        ",": 400
        ".": 600
        ":": 150
        "–": 500
    }
    wordWrap: 110
}

[mixin "menu-prefix"]
[tab 1]>[tab 1 fill]
[mixin end]

[mixin "instant3"]
    [swap]
    [instant][@use "menu-prefix"]\[Close\][tab 1 fill][instant off][sleep 200][newline]
    [instant][@use "menu-prefix"]\[Add to Watchlist\][tab 1 fill][instant off][sleep 200][newline]
    [instant][@use "menu-prefix"]\[Archive\][tab 1 fill][instant off][sleep 1600]
    [swap]
[mixin end]

[mixin "instant6"]
    [swap]
    [instant][@use "menu-prefix"]\[Escalate\][tab 1 fill][instant off][sleep 200][newline]
    [instant][@use "menu-prefix"]\[Request Clarification\][tab 1 fill][instant off][sleep 200][newline]
    [instant][@use "menu-prefix"]\[Report Filing Error\][tab 1 fill][instant off][sleep 200][newline]
    [instant][@use "menu-prefix"]\[Close\][tab 1 fill][instant off][sleep 200][newline]
    [instant][@use "menu-prefix"]\[Add to Watchlist\][tab 1 fill][instant off][sleep 200][newline]
    [instant][@use "menu-prefix"]\[Archive\][tab 1 fill][instant off][sleep 1600]
    [swap]
[mixin end]

[mixin "newdelay"]
    [sleep 10]
[mixin end]

[function "hardinstant"]

He felt a finger jab the back of his head,[sleep 200] twice.[sleep 200] The second time stronger.[sleep 300][newline]
“Hey, wake up.”[sleep 1380][newline]
[speed 48]After a moment of no reaction, he threw himself upright in [sleep 80]short\-lived, sleep\-deprived panic.[sleep 150][newline]
[custom "," 120][speed 42]
“Right, right,[sleep 400] sorry, sorry.”
[custom "," 400][sleep 400][speed 46][newline]
He rubbed his head, the sting already fading.[newline]
“Those reports won’t fill out themselves.”[sleep 150][newline]
“Yeah, yeah, I know.”[newline]
“You better, Mercury Boy.”[sleep 700][linebreak]
[custom "," 600][custom "." 750][speed 48]
As she turned [sleep 50]and walked away, [speed 46]her outerwear rubbed against the tightly\-packed chairs that lined the narrow office. Her footsteps gradually became softer until they were swallowed by the hum of background noise.[linebreak]

He rubbed his eyes and stared blankly at his screen, slowly remembering what task he was attempting to complete before he fell asleep. His gaze wandered for a moment before settling on the obvious rows and rows of reports that required manual attention. He clicked the first one at the top.[linebreak]

[custom "," 90]
[speed 30]

[repeat "─" 110 instant][newline instant][@use "newdelay"]
CARGO INCIDENT REPORT[linebreak instant][@use "newdelay"]
CASE ID : 76674539[newline instant][@use "newdelay"]
[tab 1]STATUS : PMR[newline instant][@use "newdelay"]
[repeat "─" 110 instant][newline instant][@use "newdelay"]
[tab 5]VESSEL NAME : Summer Solstice[newline instant][@use "newdelay"]
VESSEL REGISTRAR : ERSK1[newline instant][@use "newdelay"]
[tab 6]VESSEL RID : 4011[newline instant][@use "newdelay"]
[tab 4]REGESTRATION : VALID[linebreak instant][@use "newdelay"]

ROUTE[linebreak instant][@use "newdelay"]
[tab 6]DEPARTURE : Ome Spaceport, Japan, ER[newline instant][@use "newdelay"]
[tab 4]DESTINATION : Conamara Station, EP, ZU[linebreak instant][@use "newdelay"]

TIME SUBMITTED: [customremove ":"]2214\-08\-15 4:[linebreak instant]

[custom "," 450]
[custom "." 750]

[speed 20]And right [speed 25]about now [speed 30]was when h[speed 35]is brain w[speed 40]ent on aut[speed 45]opilot.[sleep 400][linebreak]

He[speed 46] used to take his job with utmost seriousness. His decisions decided if someone got fined, got warned, got visited by /someone/, or something else.[sleep 650] He used to watch himself, making sure he scrutinized every single character\-[sleep 210] [speed 44]every single [speed 39]/pixel/[speed 46].[sleep 550] But now, after a year or so–or two, or half–[sleep 200]he didn’t care. If he was sad, or mad, or angry, it reflected in his reports. His mood swings and his temper tantrums caused someone[sleep 145] [speed 49]/something/[speed 46], probably. He barely saw [sleep 120]/a/[sleep 110] report. It was [speed 50]just[speed 46][sleep 170] [speed 48]pixels[speed 46].[sleep 450][linebreak]

[custom "," 450]
[custom "." 750]

[speed 42]As he typed, he felt each key slam under his fingers, pushing back up as if to help it along to the next. He felt the hollow ring they produced through the memory of his fingertips, time and space blending with pixels and plastic. That’s all it was,[custom "," 400] pixels, pixels, pixels, and pixels.[custom "." 430] Click next.[custom "." 410] Type words.[custom "." 380] Dropdown.[custom "." 350] Close.[custom "." 320] Next.[custom "." 190] Type words.[custom "." 160] Dropdown.[custom "." 130] Request[custom "." 115] Clarification.[custom "." 100] Next.[custom "." 70] Type words.[custom "." 50] Dropdown.[custom "." 20] Escalate.[speed 35] Next.[speed 30] Type words.[speed 25] Dropdown.[speed 20] Close. It was all just pixels. All just pixels.[linebreak]

[custom "." 250]
[custom "," 390]

[speed 34]The reports blended together.[sleep 100][speed 32] The first into the second, the second into the third, and so on[ignore],[ignore off] and so on.[custom "," 300][speed 30] His hands moved even before his eyes did;[sleep 120][speed 28] opening windows,[speed 26] ticking boxes,[speed 24] discarding useless testimonies.[speed 22] Another cargo incident.[speed 20] Another minor collision.[speed 18] Another chang[linebreak instant]

[speed 50][jitter "Unknown" 2][sleep 2000][linebreak]

[custom "," 575]
[custom "." 775]
[custom "?" 775]
[speed 53]
He read and reread the word multiple times. That word wasn’t supposed to be there. He backtracked, looking for what exactly was unknown.[linebreak]

[speed 44][tab 9]DESTINATION :[sleep 300] [speed 52]Unknown Station, AR[linebreak]

[speed 42]Unknown station? Every station in the solar system was registered. It /had/ to be. You couldn’t dock with it, supply it, insure it, even acknowledge it without it being registered. The automated system should’ve rejected this report outright, he should’ve never even seen it. He looked at what came after.[linebreak]

AR. Mars. The unknown station was on Mars. He looked at the line after.[linebreak]

[speed 44]APPROXIMATE LOCATION :[sleep 300] 18°S 140°E[linebreak]

[speed 41]They even knew where it was. Why was it listed as unknown then?[linebreak]

He opened the database of all registered stations. As an ITA employee, he had access to these kinds of luxuries. Switching to coordinate search, he entered the latitude and longitude exactly as they appeared on the report. He pressed enter, and waited a few seconds for the database to filter the results.[sleep 3000][linebreak]

[tab 4]NO RESULTS FOUND[sleep 1200][linebreak]

Fine. It was a filing error then.[linebreak]

He clicked back to the report itself, and hit the actions button. A small menu unfolded near his cursor. He read the options he was presented with.[linebreak]

[@use "instant3"][linebreak]

He frowned, and read them again.[linebreak]

[@use "instant3"][linebreak]


Where was ‘report filing error’?[linebreak]
[function "hardinstant"]
He closed the program, just to reopen it a moment later. He selected the report again and opened the actions menu.[linebreak]

[@use "instant3"][linebreak]

It was still not there. Quite a few other options were missing too, actually. He tried a different report.[linebreak]

[@use "instant6"][linebreak]

The options still existed. They hadn’t done away with them, at least. He clicked back to the original report, and tried the actions button again.[linebreak]

[@use "instant3"][linebreak]

“um... Amy?” He called out, turning his head slightly, but keeping his eyes locked to the screen.[newline]
“What?”[newline]
Her voice originated from somewhere down the row, softened by distance and carpet.[newline]
“Could’ya come here for a sec, I got a problem.”[newline]
She hesitated slightly. “Be right there.”[newline]
He could hear her footsteps get louder and louder, before stopping right behind him. Her jacket once again rubbed against the office chairs.[newline]
“What?”[newline]
He pointed at the screen.[newline]
“The ‘report filing error’ button is missing.”[newline]
She took control of his mouse somewhat forcefully. She closed the dropdown, just to click on the actions menu again. The same dropdown reappeared. She was silent for a few moments.[newline]
“Did you reopen the report?”[newline]
“Yes.”[newline]
“Restart the program?”[newline]
“Yeah.”[newline]
“Did you check another report?”[newline]
“Yeah. The button’s there.”[newline]
She went quiet for a second.[newline]
“So?”[newline]
“So... it’s missing.”[newline]
She sighed.[newline]
“What do you want me to do about it?[newline]
“What?”[newline]
“What do you want me to do about it, Mercury Boy?” She accented every consonant.[newline]
“I don’t know, isn’t this like, your /thing/? Everyone asks you about computer problems.”[newline]
“Not this one. Call IT.”[newline]
Before he could reply, she left, weaving through the chairs back to her desk at the far side of the office.[linebreak]

He added the report to his watch list, closed it, and began working on the next one.[linebreak]


[sleep 700][function "end"]